### ISSUE TITLE
Preprocess rules for performance

### ISSUE THREAD

**Issue by polytypic** [polytypic/Infers#5]
Speaking of performance, the way the engine searches for a matching rule is very inefficient.  Given a desired type, the engine iterates over all the rules trying to unify the desired type with the result type of each rule.  It should be possible to effectively eliminate this iteration over all the rules by preprocessing the rules to form a kind of search tree.  There are probably articles on how prolog compilers do this, but it does not seem overly complex.

Generic types are of the form `TyCon<TyParam1, ..., TyParamN>` or `TyParam`.  For a desired type to unify with a result type they must have the same type constructor (`typedefof`) and then their type parameters must then be unified recursively or either the desired type or the result type is a type variable (trivial match).  This leads to a simple way to accelerate the search using a search tree over the result types of the rules.

The tree partitions the rules according to the type constructor of the rule result types.  Universal rules whose result type is a type variable are treated as a special case and just collected at the root.  Rules corresponding to each type constructor are then partitioned according to the type constructor of their first type parameter (if any) and so on (on the next dimension of the tree the second type parameter is used as the partitioning key).  If the rules cannot be partitioned further or there is just one rule, a leaf is formed.  So, we get a tree looking roughly like this:

```fsharp
type TypeCon = Type // For clarity below

type RuleSearchTree =
  | Leaf of List<Rule>
  | Branch of specific: Map<TypeCon, RuleSearchTree> * universal: List<Rule>
```

To search for a matching rule, the `specific` rules are tried first and then the `universal` rules.  This is only a sketch and there are more details to work out.   The preprocessing is likely to be expensive.   It can probably be done both incrementally and cached.

**Comment by VesaKarvonen** [comment]
Type (search) tree construction time currently seems to be insignificant and search time does not seem to be a major cost, meaning that the tree acceleration works.  This suggests that it is not necessarily a good idea to cache type type trees, because that would only increase persistent memory usage.

One performance improvement that could still be done to type tree construction is that currently a fully new type tree is constructed for each combined set of rules. It would be better to develop an algorithm/data structure to allow merging type trees rather than constructing them from a sequence of types (and associated values).  It is likely that merging could run in sub-linear time in most cases and could allow sharing common branches between type trees.
